apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "localrecall.fullname" . }}
  labels:
    {{- include "localrecall.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "localrecall.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "localrecall.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "localrecall.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: localrecall
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: {{ include "localrecall.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: VECTOR_ENGINE
          value: {{ .Values.config.vectorEngine | quote }}
        - name: EMBEDDING_MODEL
          value: {{ .Values.config.embeddingModel | quote }}
        - name: MAX_CHUNKING_SIZE
          value: {{ .Values.config.maxChunkingSize | quote }}
        - name: CHUNK_OVERLAP
          value: {{ .Values.config.chunkOverlap | quote }}
        - name: LISTENING_ADDRESS
          value: {{ .Values.config.listeningAddress | quote }}
        - name: FILE_ASSETS
          value: "/assets"
        - name: COLLECTION_DB_PATH
          value: "/db"
        {{- if eq .Values.config.vectorEngine "postgres" }}
        {{- if .Values.postgresql.external.existingSecret }}
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgresql.external.existingSecret }}
              key: {{ .Values.postgresql.external.existingSecretUsernameKey }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgresql.external.existingSecret }}
              key: {{ .Values.postgresql.external.existingSecretPasswordKey }}
        - name: DATABASE_URL
          value: {{ printf "postgresql://$(DB_USERNAME):$(DB_PASSWORD)@%s:%d/%s?sslmode=%s" .Values.postgresql.external.host (.Values.postgresql.external.port | int) .Values.postgresql.external.database .Values.postgresql.external.sslMode }}
        {{- else }}
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ include "localrecall.fullname" . }}
              key: database-url
        {{- end }}
        - name: HYBRID_SEARCH_BM25_WEIGHT
          value: {{ .Values.config.hybridSearch.bm25Weight | quote }}
        - name: HYBRID_SEARCH_VECTOR_WEIGHT
          value: {{ .Values.config.hybridSearch.vectorWeight | quote }}
        {{- end }}
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "localrecall.fullname" . }}
              key: openai-api-key
        - name: OPENAI_BASE_URL
          value: {{ .Values.config.openai.baseUrl | quote }}
        {{- if .Values.config.apiKeys }}
        - name: API_KEYS
          valueFrom:
            secretKeyRef:
              name: {{ include "localrecall.fullname" . }}
              key: api-keys
        {{- end }}
        {{- if .Values.config.gitPrivateKey }}
        - name: GIT_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "localrecall.fullname" . }}
              key: git-private-key
        {{- end }}
        {{- if .Values.extraEnvVars }}
        {{- toYaml .Values.extraEnvVars | nindent 8 }}
        {{- end }}
        {{- if .Values.extraEnvVarsConfigMap }}
        envFrom:
        - configMapRef:
            name: {{ .Values.extraEnvVarsConfigMap }}
        {{- end }}
        {{- if .Values.extraEnvVarsSecret }}
        - secretRef:
            name: {{ .Values.extraEnvVarsSecret }}
        {{- end }}
        volumeMounts:
        - name: data
          mountPath: /assets
          subPath: assets
        - name: data
          mountPath: /db
          subPath: db
        {{- with .Values.extraVolumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          {{- toYaml (omit .Values.livenessProbe "enabled") | nindent 10 }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          {{- toYaml (omit .Values.readinessProbe "enabled") | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      volumes:
      - name: data
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "localrecall.fullname" .) }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      {{- with .Values.extraVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
