apiVersion: v1
kind: Service
metadata:
  name: {{ include "localrecall.fullname" . }}
  labels:
    {{- include "localrecall.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
    nodePort: {{ .Values.service.nodePort }}
  {{- else }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  {{- end }}
  selector:
    {{- include "localrecall.selectorLabels" . | nindent 4 }}
